baseURL = "https://www.sivalabs.dev/"
languageCode = "en-us"
title = "SivaLabs"
uglyURLs = true
relativeURLs = true
disableKinds = ["taxonomy", "term"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
