baseURL = "https://www.sivalabs.dev/"
languageCode = "en-us"
title = "SivaLabs"
uglyURLs = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
